baseurl = "https://duck-rabbitside.github.io/"
languageCode = "en-us"
title = "The Duck-Rabbit Side"
# Define how many pages appear per site
paginate = 10
# Enable comments powered by Disqus by entering your disqus shortname
disqusShortname = "spf13"
theme = "hugo-minimalist-theme"

[params]
    site_author = "Veronica Bertollo"
    site_description = "I'm happy to present my awesome blog build by the best brother ever Samuele Bertollo!!! I will talk about finance and other things related."
    location = "United Kingdom - London"
    # All paths are relative to the baseurl. Put your files
    # somewhere in the static folder.
    avatar = "img/profile-image.png"
    header_background = "img/desk.jpg"
    header_title = "The Duck-Rabbit Side"
    copyright = "Powered by [Hugo](http://gohugo.io)."

    # Enable gogle analytics by entering your tracking code
    google_analytics = ""

[social]
    # Add your social network accounts to the profile section on the left
    # by entering your username. The links to your account will be
    # create automatically.
#    twitter   = ""
    facebook  = "https://www.facebook.com/veronica.bertollo.9"
    linkedin  = "https://www.linkedin.com/in/veronica-bertollo-66008765?authType=NAME_SEARCH&authToken=ZXNL&locale=it_IT&trk=tyah&trkInfo=clickedVertical%3Amynetwork%2CclickedEntityId%3A230099688%2CauthType%3ANAME_SEARCH%2Cidx%3A1-1-1%2CtarId%3A1484672741474%2Ctas%3Aver"
#    behance   = ""
#    dribbble  = ""
#    instagram = ""
#    github    = ""
#    gplus     = ""
